FROM python:3.9
LABEL maintainer="Vivek Katial <vivekkatial@gmail.com>"

# Environment Setup
ENV MLFLOW_VERSION 2.9.1
ENV TERM linux
ENV BUCKET s3://testBucket/
ENV MLFLOW_S3_ENDPOINT_URL https://objects.storage.unimelb.edu.au

# Install AWS CLI
WORKDIR /root
RUN curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" \
    && unzip awscli-bundle.zip \
    && ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

# Copy AWS Credentials
COPY .aws /root/.aws

# Install NGINX
RUN apt-get update && apt-get install -y nginx

# Copy NGINX Config and .htpasswd
COPY nginx.conf /etc/nginx/nginx.conf
COPY .htpasswd /etc/nginx/.htpasswd

# Install MLflow
RUN pip install --upgrade pip \
    && pip install mlflow==$MLFLOW_VERSION

# Setup MLflow Directory
RUN mkdir -p /mlflow/
WORKDIR /mlflow/

# Copy and Install Extra Requirements
COPY extra-requirements.txt /mlflow/
RUN pip install -r extra-requirements.txt

# Set permissions for .htpasswd
RUN chmod 644 /etc/nginx/.htpasswd

# Expose Port
EXPOSE 5000

# Start Command
CMD service nginx start && mlflow server \
    --backend-store-uri $BACKEND_URI \
    --default-artifact-root $BUCKET \
    --host 0.0.0.0
