experiment:
  repository: "aqc-three-sat-sim"
  github_url: "https://gitlab.unimelb.edu.au/unimelbqc/aqted/qaoa-vrp"
  cluster_uri: "/data/gpfs/projects/punim1074/qaoa-vrp"
  cluster_scratch_dir: "/scratch/punim1074/"
  cluster_provider: "unimelb_SPARTAN"
  cluster_username: "vivekkatial"
  singularity_image_uri: "ubuntu@45.113.235.110:AQTED/qaoa-vrp/qaoa-vrp-image.img"